# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  # USB controller/peripheral modules (xhci_pci, thunderbolt, usbhid, usb_storage)
  # intentionally excluded from the initrd: a flaky internal USB device (usb1-port8)
  # stalls a udev worker for ~60s during early boot, blocking systemd-udevd shutdown
  # and switch-root. Root is on NVMe with no USB-entered LUKS passphrase, so USB is
  # not needed in the initrd — it initializes in stage-2 instead, where the failing
  # port retries harmlessly in the background.
  boot.initrd.availableKernelModules = [ "nvme" "ahci" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/9aef1b00-e70f-4417-9556-34ee1d66ae36";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/70FB-ADB0";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
